#!/bin/bash

# This script is called by i3 on startup.

# Map the caps lock key to super...
setxkbmap -layout pl # -variant altgr-intl #-option caps:super
# If you don't want a us international keyboard, rather whatever keyboard
# you set in your installation, comment out the above line and uncomment
# the one below.
#setxkbmap -option caps:super

# But when it is pressed only once, treat it as escape.
Escape -e 'Super_L=Escape'

# Map the menu button to right super as well.
#xmodmap -e 'keycode 135 = Super_R'
#keycode 135 = Super_R NoSymbol Super_R

xmodmap -e "clear lock" #disable caps lock switch
#xmodmap -e "keysym Caps_Lock = Escape" #set caps_lock as escape
#write /org/gnome/desktop/input-sources/xkb-options "['caps:swapescape']"
#xmodmap -e "keysym Caps_Lock = Escape" #set caps_lock as escape
#xmodmap -e "keysym Caps_Lock = Escape"
xmodmap -e 'keycode 0x42 = Escape'
